// Single source of truth for the portfolio projects. Consumed by:
//   - Projects.vue (the detailed Projects folder, translates titleKey/descKey)
//   - PicturesGallery.vue (the "Project photos" gallery, flattens images)
//
// Titles/descriptions are i18n keys; the consuming component translates them.

const img = (file) => new URL(`./assets/img/projects/${file}`, import.meta.url).href;

export const projects = [
  {
    titleKey: "uwp",
    descKey: "uwpDescription",
    type: "Web Project",
    dateCreated: "2024-06-04",
    images: [img("weather1.webp"), img("weather2.webp"), img("weather3.webp")],
    link: "https://weather.rickmuda.nl",
    repository: "https://github.com/rickmuda/unnamed-weather-app",
  },
  {
    titleKey: "aw",
    descKey: "awDescription",
    type: "Web Project",
    dateCreated: "2022-09-20",
    images: [img("annoying1.webp"), img("annoying2.webp"), img("annoying3.webp")],
    link: "https://annoying.rickmuda.nl",
    repository: "https://github.com/rickmuda/annoying-webpage",
  },
  {
    titleKey: "wam",
    descKey: "wamDescription",
    type: "Game",
    dateCreated: "2022-11-10",
    images: [img("whack1.webp"), img("whack2.webp"), img("whack3.webp")],
    link: "https://whackamom.rickmuda.nl",
    repository: "https://github.com/rickmuda/whack-a-mom",
  },
  {
    titleKey: "gl",
    descKey: "glDescription",
    type: "Web Project",
    dateCreated: "2023-01-08",
    images: [img("gym-list.webp")],
    link: "https://gymlist.rickmuda.nl",
    repository: "https://github.com/rickmuda/gym-list",
    status: "Outdated",
  },
  {
    titleKey: "op",
    descKey: "opDescription",
    type: "Web Project",
    dateCreated: "2022-08-12",
    images: [img("one-pager.webp")],
    link: "https://onepager.rickmuda.nl",
    repository: "https://github.com/rickmuda/one-pager",
    status: "Outdated",
  },
  {
    titleKey: "sp",
    descKey: "spDescription",
    type: "Video Project",
    dateCreated: "2023-11-27",
    images: [img("snackbar-podcast.webp")],
    link: "https://www.youtube.com/watch?v=-JeNEwwF-Ms",
  },
  {
    titleKey: "us",
    descKey: "usDescription",
    type: "Game",
    dateCreated: "2024-06-07",
    images: [img("undertale-sudoku.webp")],
    link: "https://sudoku.rickmuda.nl",
    repository: "https://github.com/rickmuda/undertale-sudoku",
    status: "Outdated",
  },
  {
    titleKey: "lvt",
    descKey: "lvtDescription",
    type: "Web Project",
    dateCreated: "2023-07-30",
    images: [img("longvideotheater.webp")],
    link: "https://lvt.rickmuda.nl",
    disabled: true,
    status: "W.I.P",
  },
  {
    titleKey: "dnm",
    descKey: "dnmDescription",
    type: "Web Project",
    dateCreated: "2025-04-12",
    images: [img("dungeon and music.webp")],
    link: "https://dnm.rickmuda.nl",
    repository: "https://github.com/rickmuda/dungeons-and-music",
  },
  {
    titleKey: "syp",
    descKey: "sypDescription",
    type: "Portfolio",
    dateCreated: "2023-10-18",
    images: [img("portfolio1.webp"), img("portfolio2.webp"), img("portfolio3.webp")],
    link: "https://second.rickmuda.nl",
    repository: "https://github.com/rickmuda/second-year-portfolio",
    status: "Outdated",
  },
  {
    titleKey: "qt",
    descKey: "qtDescription",
    type: "Web Project",
    dateCreated: "2026-02-23",
    images: [img("quiet1.webp"), img("quiet2.webp"), img("quiet3.webp")],
    link: "https://quietturn.rickmuda.nl/",
  },
  {
    titleKey: "lh",
    descKey: "lhDescription",
    type: "Web Project",
    dateCreated: "2026-04-28",
    images: [img("lunar1.webp"), img("lunar2.webp"), img("lunar3.webp"), img("lunar4.webp")],
    link: "https://lunarhome.nl",
    status: "Private",
  },
  {
    titleKey: "lha",
    descKey: "lhaDescription",
    type: "Mobile App",
    dateCreated: "2026-07-13",
    images: [img("lha1.webp"), img("lha2.webp"), img("lha3.webp")],
    disabled: true,
    status: "Download only",
  },
  {
    titleKey: "gk",
    descKey: "gkDescription",
    type: "Web Project",
    dateCreated: "2026-05-28",
    images: [img("under-construction.svg")],
    disabled: true,
    status: "W.I.P",
  },
  {
    titleKey: "sr",
    descKey: "srDescription",
    type: "Mobile App",
    dateCreated: "2026-07-13",
    images: [img("SR1.webp"), img("SR2.webp"), img("SR3.webp")],
    disabled: true,
    status: "Download only",
  },
  {
    titleKey: "rfi",
    descKey: "rfiDescription",
    type: "Web Project",
    dateCreated: "2026-07-13",
    images: [img("rollforit1.webp")],
    link: "https://rollforit.rickmuda.nl",
  },
];
